openapi: 3.0.3

info:
  title: Terminal Registry Microservice
  version: 1.0.0
  description: Terminal Registry Microservice for Multi-channel Integration Layer of SW Client Project
  contact:
    name: Antonio Tarricone
    email: antonio.tarricone@pagopa.it

servers:
  - description: DEV
    url: https://mil-d-apim.azure-api.net/mil-terminal-registry
  - description: UAT
    url: https://mil-u-apim.azure-api.net/mil-terminal-registry

security:
  - bearerAuth: [ ]

paths:
  /terminals:
    parameters:
      - $ref: '#/components/parameters/RequestId'

    post:
      operationId: createTerminal
      summary: Creates a new terminal
      requestBody:
        $ref: '#/components/requestBodies/CreateTerminal'
      responses:
        "201":
          $ref: '#/components/responses/CreateTerminal'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "409":
          description: Terminal already exists
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many requests
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

    get:
      operationId: getTerminalList
      summary: Returns a page of terminals
      parameters:
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        "200":
          $ref: '#/components/responses/PageOfTerminals'
        "400":
          $ref: '#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

components:
  # ========================================================
  # Schemas
  # ========================================================
  schemas:
    # ------------------------------------------------------
    # Basic types
    # ------------------------------------------------------
    BrokerId:
      description: ID of pagoPA broker
      type: string
      pattern: "^[\\U0001-\\UD7FF\\UE000-\\UFFFD\\U10000-\\U10FFFF]{1,35}$"
      example: "97735020584"

    ChannelId:
      description: ID of pagoPA channel
      type: string
      pattern: "^[\\U0001-\\UD7FF\\UE000-\\UFFFD\\U10000-\\U10FFFF]{1,35}$"
      example: "97735020584_03"

    Enabled:
      description: True if the terminal is enabled
      type: boolean
      example: true

    ErrorCode:
      description: Error code
      type: string
      pattern: "^[A-F0-9]{9}$"
      example: "001000005"

    ErrorDescription:
      description: Error description
      type: string
      pattern: "^[ -~]{256}$"
      example: "Unexpected error from server"

    Idpay:
      description: True if the terminal is enabled to pay by means IDpay
      type: boolean
      example: true

    PageNumber:
      description: Number of the page
      type: integer
      minimum: 0
      maximum: 2147483647
      example: 1

    PageSize:
      description: Size of the page
      type: integer
      minimum: 1
      maximum: 128
      example: 20

    PagoPa:
      description: True if the terminal is enabled to pay pagoPA notices
      type: boolean
      example: true

    PayeeCode:
      description: Fiscal code of the subject that receives the payment
      type: string
      pattern: "^\\d{11}$"
      example: "06534340721"

    PspId:
      description: ID of pagoPA PSP
      type: string
      pattern: "^[\\U0001-\\UD7FF\\UE000-\\UFFFD\\U10000-\\U10FFFF]{1,35}$"
      example: "AGID_01"

    ServiceProviderId:
      description: ID of the service provider
      type: string
      pattern: "^[ -~]{1,64}$"
      example: "AGID_01"

    Slave:
      description: True if the terminal is in slave mode (it's linked to one or more cash desks)
      type: boolean
      example: true

    TerminalHandlerId:
      description: Terminal handler identifier
      type: string
      pattern: "^\\d{5}$"
      example: "45856"

    TerminalId:
      description: ID of the terminal. It must be unique per terminal handler.
      type: string
      pattern: "^\\d{8}$"
      example: "34523860"

    TerminalLocation:
      description: URL of the terminal
      type: string
      format: uri
      pattern: "^[ -~]{1,2048}$"
      example: "https://mil-d-apim.azure-api.net/mil-terminal-registry/terminals/c7a1b24b0583477292ebdbaa"

    TerminalUuid:
      description: UUID of a terminal
      type: string
      pattern: "^[0-9a-f]{24}$"
      example: "c7a1b24b0583477292ebdbaa"

    UUID:
      description: UUID
      type: string
      format: uuid
      pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      example: "d0d654e6-97da-4848-b568-99fedccb642b"

    Workstation:
      description: Label indicating the cash desk that can use a terminal
      type: string
      pattern: "^[ -~]{64}$"
      example: "cassa-1-ufficio-3"

    # ------------------------------------------------------
    # Complex types
    # ------------------------------------------------------
    Error:
      description: Error details
      type: object
      additionalProperties: false
      properties:
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        errorDescription:
          $ref: '#/components/schemas/ErrorDescription'
      required:
        - errorCode
        - errorDescription
      example:
        errorCode: "001000001"
        errorDescription: "Generic error"

    Errors:
      description: List of errors
      type: object
      additionalProperties: false
      properties:
        errors:
          type: array
          maxItems: 32
          items:
            $ref: '#/components/schemas/Error'
      required:
        - errors
      example:
        errors:
          - errorCode: "00000000A"
            errorDescription: "Generic error"
          - errorCode: "001000001"
            errorDescription: "Unexpected error from server"

    PageMetadata:
      description: Metadata of a page of data
      type: object
      additionalProperties: false
      properties:
        size:
          $ref: '#/components/schemas/PageSize'
        totalElements:
          description: Total number of items
          type: integer
          minimum: 0
          maximum: 2147483647
          example: 200
        totalPages:
          $ref: '#/components/schemas/PageNumber'
      example:
        size: 20
        totalElements: 100
        totalPages: 5

    PageOfTerminals:
      description: Page of terminals data
      type: object
      additionalProperties: false
      properties:
        terminals:
          $ref: '#/components/schemas/Terminals'
        page:
          $ref: '#/components/schemas/PageMetadata'
      example:
        terminals:
          - terminalUuid: "c7a1b24b0583477292ebdbaa"
            serviceProviderId: "AGID_01"
            terminalHandlerId: "45856"
            terminalId: "34523860"
            enabled: true
            payeeCode: "06534340721"
            slave: true
            workstations:
              - "cassa-1-ufficio-3"
              - "cassa-2-ufficio-3"
            pagoPa: true
            pagoPaConf:
              pspId: "AGID_01"
              brokerId: "97735020584"
              channelId: "97735020584_03"
            idpay: false
          - terminalUuid: "635edc54ab35f303668bbe7e"
            serviceProviderId: "AGID_01"
            terminalHandlerId: "45856"
            terminalId: "34523865"
            enabled: true
            payeeCode: "06534340721"
            slave: true
            workstations:
              - "cassa-3-ufficio-3"
              - "cassa-4-ufficio-3"
            pagoPa: true
            pagoPaConf:
              pspId: "AGID_01"
              brokerId: "97735020584"
              channelId: "97735020584_03"
            idpay: false
        page:
          size: 2
          totalElements: 5
          totalPages: 3

    PagoPaConf:
      description: PagoPa additional information
      type: object
      additionalProperties: false
      properties:
        pspId:
          $ref: '#/components/schemas/PspId'
        brokerId:
          $ref: '#/components/schemas/BrokerId'
        channelId:
          $ref: '#/components/schemas/ChannelId'
      required:
        - pspId
        - brokerId
        - channelId
      example:
        pspId: "AGID_01"
        brokerId: "97735020584"
        channelId: "97735020584_03"

    Terminal:
      description: Data of a terminal
      type: object
      additionalProperties: false
      properties:
        terminalHandlerId:
          $ref: '#/components/schemas/TerminalHandlerId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        enabled:
          $ref: '#/components/schemas/Enabled'
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
        slave:
          $ref: '#/components/schemas/Slave'
        pagoPa:
          $ref: '#/components/schemas/PagoPa'
        pagoPaConf:
          $ref: '#/components/schemas/PagoPaConf'
        idpay:
          $ref: '#/components/schemas/Idpay'
      required:
        - terminalHandlerId
        - terminalId
        - enabled
        - payeeCode
        - slave
        - pagoPa
        - idpay
      example:
        terminalHandlerId: "45856"
        terminalId: "34523860"
        enabled: true
        payeeCode: "06534340721"
        slave: true
        pagoPa: false
        idpay: true

    Terminals:
      description: List of terminals
      type: array
      maxItems: 64
      items:
        $ref: '#/components/schemas/TerminalExt'
      example:
        - terminalUuid: "c7a1b24b0583477292ebdbaa"
          serviceProviderId: "AGID_01"
          terminalHandlerId: "45856"
          terminalId: "34523860"
          enabled: true
          payeeCode: "06534340721"
          slave: true
          workstations:
            - "cassa-1-ufficio-3"
            - "cassa-2-ufficio-3"
          pagoPa: true
          pagoPaConf:
            pspId: "AGID_01"
            brokerId: "97735020584"
            channelId: "97735020584_03"
          idpay: false
        - terminalUuid: "635edc54ab35f303668bbe7e"
          serviceProviderId: "AGID_01"
          terminalHandlerId: "45856"
          terminalId: "34523865"
          enabled: true
          payeeCode: "06534340721"
          slave: true
          workstations:
            - "cassa-3-ufficio-3"
            - "cassa-4-ufficio-3"
          pagoPa: true
          pagoPaConf:
            pspId: "AGID_01"
            brokerId: "97735020584"
            channelId: "97735020584_03"
          idpay: false

    TerminalExt:
      description: Extended data of a terminal
      type: object
      additionalProperties: false
      properties:
        terminalUuid:
          $ref: '#/components/schemas/TerminalUuid'
        serviceProviderId:
          $ref: '#/components/schemas/ServiceProviderId'
        terminalHandlerId:
          $ref: '#/components/schemas/TerminalHandlerId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        enabled:
          $ref: '#/components/schemas/Enabled'
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
        slave:
          $ref: '#/components/schemas/Slave'
        workstations:
          $ref: '#/components/schemas/Workstations'
        pagoPa:
          $ref: '#/components/schemas/PagoPa'
        pagoPaConf:
          $ref: '#/components/schemas/PagoPaConf'
        idpay:
          $ref: '#/components/schemas/Idpay'
      required:
        - terminalUuid
        - serviceProviderId
        - terminalHandlerId
        - terminalId
        - enabled
        - payeeCode
        - slave
        - workstations
        - pagoPa
        - idpay
      example:
        terminalUuid: "c7a1b24b0583477292ebdbaa"
        serviceProviderId: "AGID_01"
        terminalHandlerId: "45856"
        terminalId: "34523860"
        enabled: true
        payeeCode: "06534340721"
        slave: true
        workstations:
          - "cassa-1-ufficio-3"
          - "cassa-2-ufficio-3"
        pagoPa: true
        pagoPaConf:
          pspId: "AGID_01"
          brokerId: "97735020584"
          channelId: "97735020584_03"
        idpay: true

    Workstations:
      description: List of cash desk labels
      type: array
      maxItems: 32
      items:
        $ref: '#/components/schemas/Workstation'
      example:
        - "cassa-1-ufficio-3"
        - "cassa-2-ufficio-3"

  # ========================================================
  # Request bodies
  # ========================================================
  requestBodies:
    CreateTerminal:
      description: Request to create a new terminal
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Terminal'

  # ========================================================
  # Parameters
  # ========================================================
  parameters:
    PageNumber:
      name: page
      in: query
      description: Number of the requested page of data
      required: true
      schema:
        $ref: '#/components/schemas/PageNumber'

    PageSize:
      name: size
      in: query
      description: Size of the requested page of data
      required: true
      schema:
        $ref: '#/components/schemas/PageSize'

    RequestId:
      name: RequestId
      in: header
      description: Request Id that will be logged by services
      required: true
      schema:
        $ref: '#/components/schemas/UUID'

  # ========================================================
  # Responses
  # ========================================================
  responses:
    CreateTerminal:
      description: Response of create terminal operation
      headers:
        Location:
          description: URL of the terminal
          required: true
          schema:
            $ref: '#/components/schemas/TerminalLocation'

    Error:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'

    PageOfTerminals:
      description: Page of terminals data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PageOfTerminals'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT